//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arabic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ط.
        /// </summary>
        public static string _6aa {
            get {
                return ResourceManager.GetString("_6aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ح.
        /// </summary>
        public static string _7aa {
            get {
                return ResourceManager.GetString("_7aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ُ.
        /// </summary>
        public static string _9ameh {
            get {
                return ResourceManager.GetString("_9ameh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ع.
        /// </summary>
        public static string aien {
            get {
                return ResourceManager.GetString("aien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ا.
        /// </summary>
        public static string alef {
            get {
                return ResourceManager.GetString("alef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أ.
        /// </summary>
        public static string alef_hamze_foq {
            get {
                return ResourceManager.GetString("alef_hamze_foq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إ.
        /// </summary>
        public static string alef_hamze_t7t {
            get {
                return ResourceManager.GetString("alef_hamze_t7t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آ.
        /// </summary>
        public static string alef_mamdodeh {
            get {
                return ResourceManager.GetString("alef_mamdodeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ى.
        /// </summary>
        public static string alef_maqsora {
            get {
                return ResourceManager.GetString("alef_maqsora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الله.
        /// </summary>
        public static string ALLAH {
            get {
                return ResourceManager.GetString("ALLAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ب.
        /// </summary>
        public static string baa {
            get {
                return ResourceManager.GetString("baa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.
        /// </summary>
        public static string dal {
            get {
                return ResourceManager.GetString("dal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ض.
        /// </summary>
        public static string ddad {
            get {
                return ResourceManager.GetString("ddad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ف.
        /// </summary>
        public static string faa {
            get {
                return ResourceManager.GetString("faa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to َ.
        /// </summary>
        public static string fatha {
            get {
                return ResourceManager.GetString("fatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ج.
        /// </summary>
        public static string gem {
            get {
                return ResourceManager.GetString("gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غ.
        /// </summary>
        public static string ghien {
            get {
                return ResourceManager.GetString("ghien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ه.
        /// </summary>
        public static string haa {
            get {
                return ResourceManager.GetString("haa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ء.
        /// </summary>
        public static string hamzeh {
            get {
                return ResourceManager.GetString("hamzeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ك.
        /// </summary>
        public static string kaf {
            get {
                return ResourceManager.GetString("kaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ِ.
        /// </summary>
        public static string kasra {
            get {
                return ResourceManager.GetString("kasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خ.
        /// </summary>
        public static string khaa {
            get {
                return ResourceManager.GetString("khaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ل.
        /// </summary>
        public static string lam {
            get {
                return ResourceManager.GetString("lam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        public static string mem {
            get {
                return ResourceManager.GetString("mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ن.
        /// </summary>
        public static string non {
            get {
                return ResourceManager.GetString("non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ق.
        /// </summary>
        public static string qaf {
            get {
                return ResourceManager.GetString("qaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.
        /// </summary>
        public static string raa {
            get {
                return ResourceManager.GetString("raa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ص.
        /// </summary>
        public static string sad {
            get {
                return ResourceManager.GetString("sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to س.
        /// </summary>
        public static string sen {
            get {
                return ResourceManager.GetString("sen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ّ.
        /// </summary>
        public static string shadeh {
            get {
                return ResourceManager.GetString("shadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ش.
        /// </summary>
        public static string shen {
            get {
                return ResourceManager.GetString("shen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ْ.
        /// </summary>
        public static string sokon {
            get {
                return ResourceManager.GetString("sokon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ت.
        /// </summary>
        public static string taa {
            get {
                return ResourceManager.GetString("taa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ة.
        /// </summary>
        public static string taa_marbota {
            get {
                return ResourceManager.GetString("taa_marbota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ث.
        /// </summary>
        public static string thaa {
            get {
                return ResourceManager.GetString("thaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٌ.
        /// </summary>
        public static string tnoen_9amma {
            get {
                return ResourceManager.GetString("tnoen_9amma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ً.
        /// </summary>
        public static string tnoen_fatha {
            get {
                return ResourceManager.GetString("tnoen_fatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٍ.
        /// </summary>
        public static string tnoen_kasra {
            get {
                return ResourceManager.GetString("tnoen_kasra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string wow {
            get {
                return ResourceManager.GetString("wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ؤ.
        /// </summary>
        public static string wow_hamzeh {
            get {
                return ResourceManager.GetString("wow_hamzeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ي.
        /// </summary>
        public static string yaa {
            get {
                return ResourceManager.GetString("yaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ئ.
        /// </summary>
        public static string yaa_hamzeh {
            get {
                return ResourceManager.GetString("yaa_hamzeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذ.
        /// </summary>
        public static string zal {
            get {
                return ResourceManager.GetString("zal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ز.
        /// </summary>
        public static string zay {
            get {
                return ResourceManager.GetString("zay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظ.
        /// </summary>
        public static string zhaa {
            get {
                return ResourceManager.GetString("zhaa", resourceCulture);
            }
        }
    }
}
